#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

BUILD_TMP_DIR=svn

if [ ! -d ~/$BUILD_TMP_DIR/work ]; then
    mkdir ~/$BUILD_TMP_DIR/work
fi

build=~/$BUILD_TMP_DIR/work/build.log

GTL=$(git rev-parse --show-toplevel)

if [ -z "$GTL" ];
then
    make $@ |& tee $build
else
    make -C $GTL $@ |& tee $build
fi

echo $build

if [ -s $build ];
then
    $(cat $build | fzy -x $SCRIPT_DIR/ned)
fi
